### ISSUE TITLE
Network train/predict can fail

### ISSUE THREAD

**Issue by benetis** [zenecture/neuroflow#4]
net(x) (prediction) or
net.train(xs,ys) (training)

can fail during these operations. Lets say xs size dont match up with network layout or for prediction given vector x doesn't have required length (those are exceptions, coming from breeze)

IMHO, these operations should handle the errors and just return `Try` or `Either`

edit: removed  `Validation` as it is not included in default lib

**Comment by bogdanski** [comment]
So, finally had the chance to work on this one. 

1. Now, calling `net.train` returns a `Try[Run]` with basic info about the run, instead of `Unit`.

```scala
case class Run(startTime: Long, endTime: Long, iterations: Int) // more fields?

val result: Try[Run] = net.train(xs, ys)

result match {
  case Success(rn) => // ...
  case Failure(ex) => // ...
}
```

2. I played around with wrapped Try/Either monads for prediction for a while, making net a function from `In => Try[Out]`, and I dislike the idea, because it needs implicit unwrapping to interop smoothly with Breeze structures. I'd rather adopt Breezes' approach here, i. e. fail fast instead of wrapping into monadic structures, leaving error handling to the user in the end. Example:

```scala
    val inVec: DenseVector[Double] = ???

    val prod1: DenseVector[Double] = net(inVec) *:* inVec // Interop with Breeze inline

    val tryVec: Try[DenseVector[Double]] = Try { net(inVec) } // assume net returns DenseVec wrapped in monadic Try

    val prod2: DenseVector[Double] = tryVec *:* inVec // [error] XOR.scala:66: could not find implicit value for parameter op: breeze.linalg.operators.OpMulScalar.Impl2[scala.util.Try[breeze.linalg.DenseVector[Double]],breeze.linalg.DenseVector[Double],That]

    implicit def TryVecToVec[V](v: Try[DenseVector[V]]): DenseVector[V] = v.get // would need this to solve, but I'd rather leave type signature clean, and fail fast at runtime, just like multiplying wrong matrices in Breeze.
```

Thanks for the input.

**Comment by benetis** [comment]
thanks for the update
